var GAME_LEVELS = [
  ["                                   !x                                           ",
   "                                   !x                                           ",
   "                                   !x                                           ",
   "                                   !x                                           ",
   "                                   !x                                           ",
   "xxx                                !x x                                      xxx",
   "xxx                                !x x                                      xxx",
   "xxx                                !x x                                      xxx",
   "xxx                                !x x                 oo                   xxx",
   "xxx                        xx      !x x                 xx                   xxx",
   "xxx                      xxxx      !x x                xxxx                  xxx",
   "xxx                    xxxxxx      !x x  o              xx                o  xxx",
   "xxx                  xxxxxxxx      !x x xx              xx                xx xxx",
   "xxx                xxxxxxxxxx      !x x                 xx                   xxx",
   "xxx              xxxx!xx!xxxx      !x x               xxxxxx                 xxx",
   "xxx            xxxxx!xxxx!xxx      !xxxxxxxx            xx              xxxxxxxx",
   "xxx @        xxxxxxxx!!!!xxxx      !xxxxxxxx            xx              xxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx      !xxxxxxxx            xx              xxxxxxxx",
   "xxxxxxxxxxxxxxxxx!xxxxxxxxxxx      !xxxxxxxxxxxx     xxxxxxxx     xxxxxxxxxxxxxx",
   "xx!                                !xx                                       xxx",
   "xx!                                !xx                                       xxx",
   "xx!              o                 !xx                                       xxx",
   "xx!     xxx!xxxxxxxxxxx!xxxxxxxxxxx!xx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xx!     xxx!xxxxxxxxxxx!xxxxxxxxxxx!xx           xxxx!xxxxx!xxxxx!xxxxx!xxxxxxxx",
   "xx!        v           v           v       xx        v     v     v     v     xxx",
   "xx!                                        xx                                xxx",
   "xx!                                        xx                                xxx",
   "xx!                o o   o o               xx                              o xxx",
   "xxxxxxxxxx!!!xxxxxxxxxx!xxxxxxxxxxx!!!xxxxxxxxxxxxxx!!!xxx!!!xxx!!!xxx!!!xxxxxxx",
   "xxxxxxxxxx!!!xxxxxxxxxx!xxxxxxxxxxx!!!xxxxxxxxxxxxxx!!!xxx!!!xxx!!!xxx!!!xxxxxxx"],
  ["   !! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!",
   "   !!@!!  v             v                 v                                                                     !!",
   "   !! !!                                                                                                        !!",
   "   !! !!                                                                                                      yy!!",
   "   !! !!                                                                                                        !!",
   "   !! !!                                                                    o o   o o   o o                     !!",
   "   !! !!                                                                    o o   o o   o o                     !!",
   "   !! !!                                                                                                        !!",
   "   !! !!                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!",
   "   !! !!                                                                                                        !!",
   "   !! !!                                                                                                        !!",
   "   !! !!                                 o o                                                                    !!",
   "   !! !!                                 xxx                                                                    !!",
   "   !! !!=    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =   !!",
   "   !! !!   =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =!!",
   "   !! !!=    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =   !!",
   "   !! !!               xxx                                                                                      !!",
   "   !! !!=    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =   !!",
   "   !! !!   =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =!!",
   "   !! !!=    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =   !!",
   "   !! !!xxx                                                                                                     !!",
   "!!!!x x!=    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =   !!",
   "!!!!x x!   =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =!!",
   "!!!!x x!=    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =    =   !!",
   "xxxxx xxxxxxxxxxxx                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!",
   "x                                    x  o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o   o       !!",
   "x                                    x                                                                          !!",
   "x                                    x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x      !!",
   "x                                    x  x   x   x   x   x   x   x   x   x   x   x   x   x   x   x   x   x       !!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx!!"],
  ["                                                                                                              ",
   " @        y                                                                                                    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     o o ",
   "                                                                                                              ",
   "                                                                                                              ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                          x                          x                                        ",
   "                             o            x            o             x           o                            ",
   "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "      vvxxxx            o o            xxxxvv     vvxxxxxvv     vvxxxx            yyy            xxxxvv       ",
   "          xxxx                       xxxx             x             xxxx                       xxxx           ",
   "x         vvxxxx       xxxxx       xxxxvv     x               x     vvxxxx       xxxxx       xxxxvv          x",
   "              xxxx               xxxx                                   xxxx               xxxx               ",
   "              vvxxxx           xxxxvv                 x                 vvxxxx           xxxxvv               ",
   "                                                                                                              ",
   "     x                                                                                                  x     ",
   "                                                o o         o o                                               ",
   "                                               xxxx         xxxx                                              ",
   "                                                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                             xxxxx xxxxx xxxxx      xxxxx xxxxx xxxxxx xxxx   xx   xx                         ",
   "                             x     x       x        x  xx x     x    x x  xx   xx xx                          ",
   "                             x  xx xxx     x        xxx   xxx   xxxxxx x    x   xxx                           ",
   "                             x   x x       x        x xx  x     x    x x  xx     x                            ",
   "                             xxxxx xxxxx   x        x   x xxxxx x    x xxxx      x                            ",
   "                                                                                                              ",
   "                                                                                                              ",
   "             o                                                                                                ",
   "                                                                                                              ",
   "          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        ",
   "                                                                                                              "],
  ["vvvvvvv  vvvvvvvvvvvvv  vvvvvvv",
   "                               ",
   "                               ",
   "                               ",
   "                               ",
   "              @                ",
   "   o         xxx          o o  ",
   "xxxxxxxxxxxxx   xxxxxxxxxxxxxxx"]
  ["                                                 ",
   "xx   xx xxxxx x   x       x   x xxxxx x    x xx  ",
   " xx xx  x   x x   x       x   x   x   xxx  x xx  ",
   "  xxx   x   x x   x       x x x   x   x xx x xx  ",
   "   x    x   x x   x       x x x   x   x  xxx     ",
   "   x    xxxxx xxxxx       xxxxx xxxxx x    x xx  ",
   "                                                 ",
   "  @                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
